### ISSUE TITLE
nicer cosi check output

### ISSUE THREAD

**Issue by ineiti** [dedis/cosi#12]
When running `cosi check`, the output should include the comment of the server, so that one can see which servers are trying to connect and sign.

**Comment by liamsi** [comment]
The typical golang way would be to only show output if there was an error (but we can of course do it differently if it makes sense here)

**Comment by ineiti** [comment]
The `check` option is typically used for debugging and looking whether the system is running correctly or not. If you want, you can add a `if dbg.DebugVisible() > 0` in front of the prints, but for me the `check` option is supposed to be verbose. At least till most of the bugs are out. Once it works more nicely, we can reduce the verbosity.

**Comment by nikkolasg** [comment]
Is it ok to close ? PR #13 has been merged.
