### ISSUE TITLE
Tag versioning

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cosi#16]
When we release a new version, we should create _annotated tags_ and not _lightweight tags_. This issue has been raised when trying to create debian packages automatically, which determines the version using _annotated tags_. More info in [0].
To do that, we simply need to append the `-a` option in our `cross_compile.sh` script, that should do the trick.

[0] https://github.com/russross/blackfriday/issues/196

**Comment by ineiti** [comment]
#21
