### ISSUE TITLE
Add version-function to API

### ISSUE THREAD

**Issue by ineiti** [dedis/cosi#25]
In order to verify what versions of the server-software are running, we should add an API that only returns the version of the installation. Could also be used to return some stats like messages signed, uptime, ...

**Comment by nikkolasg** [comment]
Yep. For me this feature definitely has its place into a Service :)

**Comment by ineiti** [comment]
We could add a 'general' service which adds all this kind of information...

**Comment by nikkolasg** [comment]
I kind envision the thing where this service (whatever the name is) will also serve as some kind of monitoring API, to know how many connections, bandwitdth etc etc. (and of course basic information like address + version ). Like Monitor or Information . Naming is hard for general things.

**Comment by ineiti** [comment]
This will be taken care of by cothority-status-service. But the cosi-binary should also be able to read the status using that service.
