### ISSUE TITLE
Verification Function for signing.

### ISSUE THREAD

**Issue by nikkolasg** [dedis/cosi#59]
We implemented a fork of cosi in `dedis/cothority/protocols/swupdate/` with the possiblity of giving a verification function so each node has the possiblity to say if he is OK to sign a statement or not (this is obviously useful so I won't go listing all the advantages).
I believe the implementation is done in `nsdi_base` in the cothority repo.

**Comment by ineiti** [comment]
Best to put that together with the soon-to-be-remerged-cosi-cothority...

**Comment by jeffallen** [comment]
These are done in dedis/cothority.
