### ISSUE TITLE
Binary distributions

### ISSUE THREAD

**Issue by ineiti** [dedis/cosi#7]
Add binary distributions for
- Debian - https://github.com/Debian/dh-make-golang
- RedHat
- MacBrew - https://github.com/samertm/homebrew-go-resources
- MacPorts

**Comment by nikkolasg** [comment]
Homebrew formula created and made a PR to maintainers at https://github.com/Homebrew/homebrew-core/pull/1404

**Comment by ineiti** [comment]
Cosi is dead - long live cothority/cosi ;)
