### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by liamsi** [dedis/cosi#8]
Run `go test -race ./...` to reproduce it `go test -race -p=1 ./...` works though (maybe that's sufficient here?).

**Comment by ineiti** [comment]
Only shows up in go 1.6.1 - seems the race-checker also includes maps now.

**Comment by liamsi** [comment]
We could try to run our nodes with the `-race` flag enabled and run `cosi check` with go-rountines enabled to see how/if this impacts the cosi servers..

**Comment by liamsi** [comment]
Linus and me run our servers with the race detector on and sent a lot of requests (using `cosi check`):
We don't see any race condition popping up but the servers aren't reachable randomly.

**Comment by liamsi** [comment]
If we restart servers it sometimes works. Linus suspects it's related to the fact that we re-use once established connections.

**Comment by ineiti** [comment]
I would say we close this because it works with `-p=1` what we use anyway.

**Comment by liamsi** [comment]
I'm also OK with closing this one since we tested the binaries in action (and not only the tests)
